### PR TITLE
small cleanups and a one new option

### PR DESCRIPTION
**Pull request by maciejsszmigiero**
First, thanks for giving cc-tool a new home!

This pull request contains few small cleanups and a one new option to allow flashing some Intel HEX
files generated by TI ZNP build process.

Please look at individual commit messages for details, thanks.

### CODE REVIEW

**Comment by dashesy** [comment]
Thanks for the new option, as well as the clean up!

Now that `./configure` is removed the new build process is to use `./boostrap` which is based on `autoreconf`.
It requires a new package:

    apt-get install dh-autoreconf

I am not good with autottools, and do not know what is the correct way. I do not want to break if someone has a build process depending on `./configure` but if it is deprecated we should update.

**Comment by maciejsszmigiero** [comment]
> Now that ./configure is removed the new build process is to use ./boostrap which is based on
> autoreconf.
> I am not good with autottools, and do not know what is the correct way. 

The ./boostrap script simply regenerates (or creates) the ./configure script and its friends from
configure.ac and Makefile.am files.
After this step, ./configure should be run as previously.

This is actually a standard way to maintain Autotools-based repository (the files that this cleanup
has removed are normally shipped pregenerated only in release tarballs) -
see for example the OpenSC repository located here: https://github.com/OpenSC/OpenSC

> It requires a new package:
> apt-get install dh-autoreconf

This is dependent on a particular distribution that a developer uses
(Gentoo, for example, being a source-based distribution has all these tools installed by default).

But people doing work on Autotools-based projects normally have these packages installed because
one always has to regenerate ./configure script and so after changing the 'master' configure.ac or Makefile.am files.

**Comment by dashesy** [comment]
Thanks for something new to learn, and for the PR.

**Comment by maciejsszmigiero** [comment]
Thanks for your quick response and merging this PR.

**Pull request merged**
