### PR TITLE
Support Mac OS 12.5

### PR DESCRIPTION
**Pull request by andrei-golubov**

### CODE REVIEW

**Comment by dashesy** [comment]
Boost 1.39 is a little too old! Thank for the PR. I merge this, let's hope new boost doesn't break in other systems. If it does we can find another version, somewhat newer than 1.39.

**Comment by bnutz** [comment]
> Boost 1.39 is a little too old! Thank for the PR. I merge this, let's hope new boost doesn't break in other systems. If it does we can find another version, somewhat newer than 1.39.

Boost 1.79 is a little too new! I've been building directly on a Raspberry Pi and currently the latest version available on that is 1.74:
https://packages.debian.org/bullseye/libboost-all-dev

So was getting version error during `./configure`
```
checking for Boost headers version >= 1.79.0... no
configure: error: cannot find Boost headers version >= 1.79.0
```

I needed to manually edit the BOOST_REQUIRE in `configure.ac` to:
`BOOST_REQUIRE([1.74])`

After this was able to successfully build the tool and flash my device.
Hope this helps anyone else out there!

**Comment by dashesy** [comment]
@bnutz please feel free to send a PR. Maybe 1.74 is a good compromise to update boost but keep it working on older systems.
@andrei-golubov can you try to see if 1.74 works on Mac OS?

**Comment by andrei-golubov** [comment]
@dashesy Ok, I'll check it out today.

**Comment by andrei-golubov** [comment]
> @bnutz please feel free to send a PR. Maybe 1.74 is a good compromise to update boost but keep it working on older systems. @andrei-golubov can you try to see if 1.74 works on Mac OS?

It works

**Comment by dashesy** [comment]
Thanks for checking this out. I will merge the changes now.

**Pull request merged**
